# apiVersion: v1
# kind: Namespace
# metadata:
#   name: getting-started-operator
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started-operator
  namespace: getting-started-operator
spec:
  selector:
    matchLabels:
      app: getting-started-operator
  replicas: 1 
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: getting-started-operator
    spec:
      containers:
      - name: getting-started-operator
        image:  malek1zaag/my-operator:v0.1
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        imagePullPolicy: Always
      serviceAccountName: operator-serviceaccount
